# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51e7c6573917f21989daa89ffeee06971acdf8c46ff1fb0b37e055a74e7045da2368d7d53dadfb3ae4980d5d060aa28425c014df9e68d0701881afcf60f6a5d4

test:
  secret_key_base: 8bd898c9b30b1697fef2a152fd04842b413ad5d2d8cdf4987d6e9fc4e38a3b7048fe529bb860e065c17667e0a798eb1d3af9f4606240b11c77c59ec900a5c6b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
